// Copyright The Pit Project Owners. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Please see https://openpit.dev and the OWNERS file for details.
//
// Base64-inlines the generated `openpit_js_bg.wasm` into a TypeScript module
// (`src-ts/wasm/openpit_js_inline.ts`). The browser loader imports these bytes
// and instantiates synchronously, so the published browser bundle carries the
// wasm with no `fetch`, no `fs`, and no separate asset to host - it works on any
// CDN and in edge isolates (Cloudflare Workers) with zero configuration.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const wasmDir = resolve(here, "..", "src-ts", "wasm");
const wasmInput = join(wasmDir, "openpit_js_bg.wasm");
const outFile = join(wasmDir, "openpit_js_inline.ts");

if (!existsSync(wasmInput)) {
  throw new Error(
    `[inline-wasm] generated wasm not found: ${wasmInput} (run build:wasm first)`,
  );
}

const base64 = readFileSync(wasmInput).toString("base64");

const module = `// AUTO-GENERATED by scripts/inline-wasm.mjs. Do not edit.
/* eslint-disable */
// prettier-ignore
export const wasmBase64 =
  "${base64}";

/**
 * Decodes the inlined wasm module to raw bytes.
 *
 * Uses Node's Buffer when available (no global \`atob\`), otherwise the
 * standard-library \`atob\` present in browsers, Deno, Bun, and Workers.
 */
export const wasmBytes = (): Uint8Array => {
  if (typeof Buffer !== "undefined") {
    return new Uint8Array(Buffer.from(wasmBase64, "base64"));
  }
  const binary = atob(wasmBase64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
};
`;

writeFileSync(outFile, module);
console.log(`[inline-wasm] wrote ${outFile} (${base64.length} base64 chars)`);
